version: 0.2

phases:
  install:
    commands:
      - echo Installing nginx...
      - sudo yum update -y
      - sudo yum install nginx -y
      - mkdir -p /usr/share/nginx/html
  build:
    commands:
      - echo "Build started on $(date)"
      - cp index.html /usr/share/nginx/html/
  post_build:
    commands:
      - echo Configuring NGINX
artifacts:
  files:
    - /usr/share/nginx/html/index.html
